# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Maria Basia
title: Junior Software Developer
email: maria.basia1@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Maria-Basia
linkedin_username: maria-basia

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)


# About Section
# about_title: About Me
about_content: | # this will include new lines to allow paragraphs
  Hi I'm Maria, a Junior Software Developer, seamlessly blending technical skills with UX expertise gained from an 8-year career in UX Research
  and Accessibility. Recently graduating from Makers Software Bootcamp, I worked on full-stack projects, handling both frontend 
  and backend development within tight timelines. Experienced in client-facing and in-house roles, with strong communication, 
  analytical, problem-solving, and strategic skills, as well as collaborating with cross-functional Product teams. 
  <br><br>
  **Tech skills:** <br>
  ![Python](https://img.shields.io/badge/python-3670A0?style=flat&logo=python&logoColor=ffdd54) 
  ![JavaScript](https://img.shields.io/badge/javascript-%23323330.svg?style=flat&logo=javascript&logoColor=%23F7DF1E) 
  ![Swift](https://img.shields.io/badge/swift-F54A2A?style=flat&logo=swift&logoColor=white) 
  ![HTML5](https://img.shields.io/badge/html5-%23E34F26.svg?style=flat&logo=html5&logoColor=white) 
  ![CSS3](https://img.shields.io/badge/css3-%231572B6.svg?style=flat&logo=css3&logoColor=white) 
  ![React](https://img.shields.io/badge/react-%2320232a.svg?style=flat&logo=react&logoColor=%2361DAFB) 
  ![Flask](https://img.shields.io/badge/flask-%23000.svg?style=flat&logo=flask&logoColor=white)
  ![SWIFTUI](https://img.shields.io/badge/SwiftUI-2-blue)
  ![Express.js](https://img.shields.io/badge/express.js-%23404d59.svg?style=flat&logo=express&logoColor=%2361DAFB) 
  ![NodeJS](https://img.shields.io/badge/node.js-6DA55F?style=flat&logo=node.js&logoColor=white) 
  ![MongoDB](https://img.shields.io/badge/-MongoDB-4DB33D?style=flat&logo=mongodb&logoColor=FFFFFF)
  ![PostgreSQL](https://img.shields.io/badge/postgresql-4169e1?style=for-the-badge&logo=postgresql&logoColor=white)
  ![Git](https://img.shields.io/badge/git-%23F05033.svg?style=flat&logo=git&logoColor=white) 
  ![GitHub](https://img.shields.io/badge/github-%23121011.svg?style=flat&logo=github&logoColor=white)
  ![Docker](https://img.shields.io/badge/docker-%230db7ed.svg?style=flat&logo=docker&logoColor=white) 
  ![Render](https://img.shields.io/badge/Render-%46E3B7.svg?style=flat&logo=render&logoColor=white) <br>

  **Other skills:** <br>
  ![Arduino](https://img.shields.io/badge/-Arduino-00979D?style=flat&logo=Arduino&logoColor=white)  
  ![Confluence](https://img.shields.io/badge/confluence-%23172BF4.svg?style=flat&logo=confluence&logoColor=white) 
  ![Jira](https://img.shields.io/badge/jira-%230A0FFF.svg?style=flat&logo=jira&logoColor=white) 
  ![Figma](https://img.shields.io/badge/figma-%23F24E1E.svg?style=flat&logo=figma&logoColor=white) 
  ![Sketch](https://img.shields.io/badge/Sketch-FFB387?style=flat&logo=sketch&logoColor=black) 
  ![Invision](https://img.shields.io/badge/invision-FF3366?style=flat&logo=invision&logoColor=white) 
  ![Proto.io](https://img.shields.io/badge/Proto.io-161637?style=flat&logo=proto.io&logoColor=00e5ff) 
  ![Canva](https://img.shields.io/badge/Canva-%2300C4CC.svg?style=flat&logo=Canva&logoColor=white) 
  ![Adobe Illustrator](https://img.shields.io/badge/adobe%20illustrator-%23FF9A00.svg?style=flat&logo=adobe%20illustrator&logoColor=white) 
  ![Adobe Photoshop](https://img.shields.io/badge/adobe%20photoshop-%2331A8FF.svg?style=flat&logo=adobe%20photoshop&logoColor=white) 
  ![Adobe After Effects](https://img.shields.io/badge/Adobe%20After%20Effects-9999FF.svg?style=flat&logo=Adobe%20After%20Effects&logoColor=white)  

<br>
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: Acebook
        link: https://github.com/Maria-Basia/acebook-krypton-web-app
        
        description: | # this will include new lines to allow paragraphs
          Facebook-like web app <br>
          April 2024, 2-week project <br>
          **Tech:**  JavaScript  MERN stack  MongoDB  Express.js  React  Node.js
          
          A Facebook-like web app built with the MERN stack. Starting from a legacy codebase with account creation, login, and 
          viewing posts functionality, features were added for creating and liking posts, commenting on posts, liking comments, 
          editing password, and viewing profile details amongst others.

      - layout: top-left
        title: MakersBnB
        link: https://github.com/Maria-Basia/makersBnB_web_app
        
        description: | # this will include new lines to allow paragraphs
          AirBnB-like web app | March 2024 | 1-week project
          Tech:  Python | Flask | PostgreSQL | Pytest | HTML | CSS | 
          
          A property rental web app similar to Airbnb. The project was developed using Test-Driven Development (TDD). Key 
          features include user signup and login with sessions, viewing all property listings, detailed property pages, 
          single-night bookings, and creating new property listings.

      - layout: top-left
        title: FuryRoam 
        link: https://github.com/Maria-Basia/travel_recommendations_web_app
        
        description: | # this will include new lines to allow paragraphs
          Travel Recommendations web app | April 2024 | 2-week project
          Tech:  Python | Flask | React  | HTML | CSS | Render (deployment)
          
          Personalised travel recommendations based on user preferences and historical weather data. Multiple APIs fetch 
          relevant data, tailoring recommendations to user input, including city details and weather APIs. A map API allows 
          visual exploration of recommended cities. Logic and API request timing was refactored to reduce response time 
          leading to a seamless User Experience.   
          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
